[config]
schemaVersion = "0.0.1"

[package]
namespace = "deca"
name = "VampireCommandFramework"
versionNumber = "0.5.0"
description = "Command framework for developers to easily create universal commands for their plugins."
websiteUrl = "https://github.com/decaprime/VampireCommandFramework"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.0.668001"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = ["Gloomrot Update"]
